# Generated by Django 6.1.1 on 2026-09-29 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Problem Tag',
                'verbose_name_plural': 'Problem Tags',
                'db_table': 'problem_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('xp_reward', models.PositiveIntegerField(default=20)),
                ('description_markdown', models.TextField()),
                ('input_format', models.TextField(blank=True, default='')),
                ('output_format', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('examples', models.JSONField(default=list)),
                ('time_limit_ms', models.PositiveIntegerField(default=2000)),
                ('memory_limit_mb', models.PositiveIntegerField(default=256)),
                ('starter_templates', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='problems', to='problems.problemtag')),
            ],
            options={
                'verbose_name': 'Problem',
                'verbose_name_plural': 'Problems',
                'db_table': 'problems',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'verbose_name': 'Problem Test Case',
                'verbose_name_plural': 'Problem Test Cases',
                'db_table': 'problem_test_cases',
                'ordering': ['display_order'],
            },
        ),
    ]
