# Generated by Django 6.1.1 on 2026-09-29 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContinueLearning',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='continue_learning', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('item_type', models.CharField(default='lesson', max_length=20)),
                ('title', models.CharField(default='Binary Search', max_length=200)),
                ('module_title', models.CharField(default='Module 3 • Searching', max_length=200)),
                ('slug', models.CharField(default='binary-search', max_length=100)),
                ('progress_percentage', models.PositiveIntegerField(default=72)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Continue Learning',
                'verbose_name_plural': 'User Continue Learning',
                'db_table': 'user_continue_learning',
            },
        ),
        migrations.CreateModel(
            name='UserRecentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('lesson_completed', 'Lesson Completed'), ('problem_solved', 'Problem Solved'), ('achievement_unlocked', 'Achievement Unlocked'), ('streak_milestone', 'Streak Milestone')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recent Activity',
                'verbose_name_plural': 'User Recent Activities',
                'db_table': 'user_recent_activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateField(db_index=True)),
                ('problems_solved', models.PositiveIntegerField(default=0)),
                ('lessons_completed', models.PositiveIntegerField(default=0)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('coding_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Activity',
                'verbose_name_plural': 'User Daily Activities',
                'db_table': 'user_daily_activities',
                'ordering': ['-activity_date'],
                'unique_together': {('user', 'activity_date')},
            },
        ),
    ]
