# Generated by Django 6.1.1 on 2026-09-29 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('Searching', 'Searching'), ('Sorting', 'Sorting'), ('Arrays', 'Arrays'), ('Linked Lists', 'Linked Lists'), ('Trees', 'Trees'), ('Graphs', 'Graphs'), ('DP', 'Dynamic Programming')], default='Searching', max_length=50)),
                ('description', models.TextField()),
                ('time_complexity_best', models.CharField(default='O(1)', max_length=50)),
                ('time_complexity_avg', models.CharField(default='O(n)', max_length=50)),
                ('time_complexity_worst', models.CharField(default='O(n)', max_length=50)),
                ('space_complexity', models.CharField(default='O(1)', max_length=50)),
                ('default_dataset', models.JSONField(default=list)),
                ('implementation_code', models.JSONField(default=dict)),
                ('pseudocode', models.TextField(blank=True, default='')),
                ('advantages', models.JSONField(default=list)),
                ('limitations', models.JSONField(default=list)),
                ('when_to_use', models.TextField(blank=True, default='')),
                ('when_not_to_use', models.TextField(blank=True, default='')),
                ('common_mistakes', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Algorithm',
                'verbose_name_plural': 'Algorithms',
                'db_table': 'algorithms',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
