# Generated by Django 6.1.1 on 2026-09-29 19:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=20)),
                ('preferred_language', models.CharField(default='python', max_length=30)),
                ('default_difficulty', models.CharField(default='Easy', max_length=20)),
                ('daily_goal', models.PositiveIntegerField(default=5)),
                ('email_notifications', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('daily_reminders', models.BooleanField(default=True)),
                ('weekly_progress_summary', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('show_achievements', models.BooleanField(default=True)),
                ('show_activity', models.BooleanField(default=True)),
                ('editor_font_size', models.PositiveIntegerField(default=14)),
                ('editor_theme', models.CharField(default='vs-dark', max_length=30)),
                ('tab_size', models.PositiveIntegerField(default=4)),
                ('word_wrap', models.BooleanField(default=True)),
                ('auto_save', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
