# Generated by Django 6.1.1 on 2026-09-29 18:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='Map', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Roadmap',
                'verbose_name_plural': 'Roadmaps',
                'db_table': 'roadmaps',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('tier', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(default='Foundations', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(default='Layers', max_length=50)),
                ('estimated_hours', models.PositiveIntegerField(default=4)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('linked_course_slug', models.CharField(blank=True, default='', max_length=100)),
                ('linked_lesson_slug', models.CharField(blank=True, default='', max_length=100)),
                ('linked_tag_slug', models.CharField(blank=True, default='', max_length=100)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='roadmaps.roadmapnode')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='roadmaps.roadmap')),
            ],
            options={
                'verbose_name': 'Roadmap Node',
                'verbose_name_plural': 'Roadmap Nodes',
                'db_table': 'roadmap_nodes',
                'ordering': ['tier', 'display_order'],
                'unique_together': {('roadmap', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='UserRoadmapProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='roadmaps.roadmapnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Roadmap Progress',
                'verbose_name_plural': 'User Roadmap Progresses',
                'db_table': 'user_roadmap_progress',
                'unique_together': {('user', 'node')},
            },
        ),
    ]
