# Generated by Django 6.1.1 on 2026-09-29 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=30)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Running', 'Running'), ('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Memory Limit Exceeded', 'Memory Limit Exceeded'), ('Compilation Error', 'Compilation Error'), ('Runtime Error', 'Runtime Error')], default='Queued', max_length=30)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('memory_used_kb', models.PositiveIntegerField(default=0)),
                ('tests_passed', models.PositiveIntegerField(default=0)),
                ('tests_total', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionTestCaseResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Error', 'Error'), ('Time Limit Exceeded', 'Time Limit Exceeded')], max_length=30)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('actual_output', models.TextField(blank=True, default='')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='submissions.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_results', to='problems.problemtestcase')),
            ],
            options={
                'verbose_name': 'Submission Test Case Result',
                'verbose_name_plural': 'Submission Test Case Results',
                'db_table': 'submission_test_case_results',
            },
        ),
    ]
